"""DRF serializers for the session API.

Two views of the same model:

- SessionSummarySerializer — safe for the public list, no token.
- SessionDetailSerializer — returned on create and on token access.

The token is never included in the list endpoint. It is returned
exactly once, at creation time, as part of the create response.
"""

from __future__ import annotations

from rest_framework import serializers

from control_plane.apps.sessions_mgr.models import (
    Session,
    SessionEvent,
    SimulationCatalog,
    slug_validator,
)


class SimulationCatalogSerializer(serializers.ModelSerializer):
    class Meta:
        model = SimulationCatalog
        fields = [
            "simulation_id",
            "display_name",
            "version",
            "description",
        ]


class SessionSummarySerializer(serializers.ModelSerializer):
    """Public list view. No token."""

    class Meta:
        model = Session
        fields = [
            "id",
            "slug",
            "simulation_id",
            "simulation_version",
            "label",
            "status",
            "created_at",
            "started_at",
            "stopped_at",
        ]
        read_only_fields = fields


class SessionDetailSerializer(serializers.ModelSerializer):
    """Full view. Includes token and runtime endpoint info."""

    endpoint_url = serializers.SerializerMethodField()
    external_id = serializers.SerializerMethodField()

    class Meta:
        model = Session
        fields = [
            "id",
            "slug",
            "external_id",
            "token",
            "simulation_id",
            "simulation_version",
            "label",
            "status",
            "port",
            "pid",
            "advertised_endpoint",
            "endpoint_url",
            "config_params",
            "created_at",
            "started_at",
            "stopped_at",
        ]
        read_only_fields = fields

    def get_external_id(self, obj: Session) -> str:
        return obj.external_id()

    def get_endpoint_url(self, obj: Session) -> str:
        host = self.context.get("gateway_host", "")
        if not host:
            return ""
        return f"opc.tcp://{host}/gateway/"


class SessionCreateSerializer(serializers.Serializer):
    """Input for POST /api/sessions/.

    The client supplies the simulation_id (must exist in the catalog),
    an optional slug, an optional label, and optional config params.
    Everything else is generated by the server.

    A slug, when supplied, becomes the session's identifier in the OPC
    UA address space. Recreating with the same slug stops the prior
    session and takes over the name.
    """

    simulation_id = serializers.CharField(max_length=64)
    slug = serializers.CharField(
        max_length=64,
        required=False,
        allow_blank=True,
        default=None,
        validators=[slug_validator],
    )
    label = serializers.CharField(
        max_length=128, required=False, allow_blank=True, default="",
    )
    config_params = serializers.JSONField(required=False, default=dict)

    def validate_simulation_id(self, value: str) -> str:
        if not SimulationCatalog.objects.filter(
            simulation_id=value, is_active=True,
        ).exists():
            raise serializers.ValidationError(
                f"unknown or inactive simulation: {value}"
            )
        return value

    def validate_slug(self, value: str | None) -> str | None:
        # Normalise the empty string to None so multiple blank slugs
        # do not collide on the DB unique constraint.
        return value or None

    def validate_config_params(self, value):
        if not isinstance(value, dict):
            raise serializers.ValidationError("must be a JSON object")
        return value


class SessionEventSerializer(serializers.ModelSerializer):
    class Meta:
        model = SessionEvent
        fields = ["event", "detail", "occurred_at"]
        read_only_fields = fields